# Generated by Django 3.1.3 on 2024-03-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20240307_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profession',
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='', max_length=20, null=True),
        ),
    ]
