# Generated by Django 3.1.3 on 2024-03-07 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20240307_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='status',
            new_name='Course',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='shift',
            new_name='time',
        ),
    ]
