# Generated by Django 3.1.3 on 2024-03-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201129_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('Computer Engineering', 'Computer Engineering'), ('Instructor', 'Instructor')], default='', max_length=20, null=True),
        ),
    ]
