# Generated by Django 3.1.3 on 2024-03-06 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20240307_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ranking',
        ),
    ]
