# Generated by Django 3.1.3 on 2024-03-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_profile_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.CharField(choices=[('Computer Engineering', 'Computer Engineering'), ('Instructor', 'Instructor')], default='', max_length=20, null=True),
        ),
    ]
